/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'leojg' at '7/19/16 10:12 PM' with Gradle 2.14
 *
 * @author leojg, @date 7/19/16 10:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
